apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: user-12
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DUMMY_DATABASE_PASSWORD 
          value: admin
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
        requests:
          cpu: "50m"
          memory: "50Mi"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
          scheme: HTTP
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 10
        periodSeconds: 15
        timeoutSeconds: 1
        failureThreshold: 3
      startupProbe:
        httpGet:
          path: /healthz
          port: 80
          scheme: HTTP
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      volumeMounts:
        - name: htmldir
          mountPath: /usr/share/nginx/html/
          readOnly: true
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
            while true; do
              echo "hello world" >> /html/index.html
              sleep 5
            done
      resources:
        limits:
          cpu: "100m"
          memory: "100Mi"
        requests:
          cpu: "50m"
          memory: "50Mi"
      volumeMounts:
        - name: htmldir
          mountPath: /html
          readOnly: true
  volumes:
    - name: htmldir
      emptyDir: {}
