apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: user-12
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    resources:
      limits:
        cpu: "500m"
        memory: "500Mi"
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_USER
      valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
    - name: MYSQL_PASSWORD
      valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
    - name: MYSQL_DATABASE
      value: test_database
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: user-12
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  MYSQL_ROOT_PASSWORD: ZXN1bkAxMzEz
  MYSQL_USER: ZXNiMTkxNjA=
  MYSQL_PASSWORD: ZXN1bkAxMzEz
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: user-12
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
