apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  namespace: user-12
  labels:
    app: wordpress
spec:
  containers:
    - name: wordpress
      image: wordpress:latest
      resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
      env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-config
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: WORDPRESS_DB_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: user-12
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  WORDPRESS_DB_USER: ZXNiMTkxNjA=
  WORDPRESS_DB_PASSWORD: ZXN1bkAxMzEz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: user-12
data:
  WORDPRESS_DB_HOST: mysql-svc.user-12.svc
  WORDPRESS_DB_NAME: test_database
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: user-12
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
